### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by z0lope0z** [kaaes/spotify-web-api-android#45] opened 2015-04-10 03:09 UTC
Any plans on pushing this to maven central? Would love to help out!

**Comment by z0lope0z** [comment] 2015-04-15 10:42
hosted it on github temporarily and posting it here in case someone finds it useful
app/build.gradle
```
repositories {
    maven {
        url "https://github.com/z0lope0z/raws/raw/master"
    }
    mavenCentral()
}

dependencies {
    compile 'kaaes.spotify.webapi.android:spotify-web-api-android:0.1.0'
}
```

**Comment by winterDroid** [comment] 2015-04-17 13:29
+1

**Comment by Wolftein** [comment] 2015-04-22 17:47
+1

**Comment by jitpack-io** [comment] 2015-06-08 13:09
Btw, its possible to get it via https://jitpack.io/#kaaes/spotify-web-api-android/b0a4c2dad3

**Comment by kaaes** [comment] 2015-11-25 16:40
I think it would be good to tackle this finally. Seems like we have two options here:

* Go with [Jitpack](https://jitpack.io/) as it looks super simple!
* Publish project in [Maven Central](http://central.sonatype.org/pages/ossrh-guide.html) as it is *The Repository*

I would love to know your opinions!
(ping @d-kunin @JMPerez @thelinmichael)

**Comment by kaaes** [comment] 2015-11-25 16:44
Actually this is a duplicate of #67, I'll close this one and we can use the other

**Closed by kaaes** 2015-11-25 16:44 UTC
Labels: enhancement
